using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using CycloneGames.InputSystem.Editor;
using CycloneGames.InputSystem.Runtime;
using NUnit.Framework;
using UnityEngine;
using VYaml.Serialization;

namespace CycloneGames.InputSystem.Tests.Editor
{
    public sealed class InputCodeGenerationEditorTests
    {
        [Test]
        public void Generate_MinimalConfigurationMatchesGoldenSource()
        {
            InputConfiguration configuration = CreateMinimalConfiguration();
            int actionId = InputHashUtility.GetActionId("Gameplay", "PlayerActions", "Move");
            string expected = string.Join(
                Environment.NewLine,
                "// -- AUTO-GENERATED FILE --",
                "// Generated by CycloneGames.InputSystem. Do not edit manually.",
                string.Empty,
                "namespace Game.Input",
                "{",
                "    public static class InputActions",
                "    {",
                "        public static class Contexts",
                "        {",
                "            public const string Gameplay = \"Gameplay\";",
                "        }",
                string.Empty,
                "        public static class ActionMaps",
                "        {",
                "            public const string GlobalActions = \"GlobalActions\";",
                "            public const string PlayerActions = \"PlayerActions\";",
                "        }",
                string.Empty,
                "        public static class Actions",
                "        {",
                $"            public const int Gameplay_Move = {actionId}; // FNV-1a32: Gameplay/PlayerActions/Move",
                "        }",
                "    }",
                "}",
                string.Empty);

            bool generated = InputConstantsCodeGenerator.TryGenerate(
                configuration,
                "Game.Input",
                out string source,
                out string error);

            Assert.That(generated, Is.True, error);
            Assert.That(source, Is.EqualTo(expected));
        }

        [Test]
        public void Generate_EscapesStringsKeywordsAndBakesStableIds()
        {
            InputConfiguration configuration = CreateCodegenConfiguration();

            bool generated = InputConstantsCodeGenerator.TryGenerate(
                configuration,
                "class.generated",
                out string source,
                out string error);

            Assert.That(generated, Is.True, error);
            Assert.That(source, Does.Contain("namespace @class.generated"));
            Assert.That(source, Does.Contain("Game\\\"play\\\\Mode"));
            Assert.That(source, Does.Not.Contain("InputHashUtility"));
            Assert.That(source, Does.Not.Contain("_Id ="));

            int expectedId = InputHashUtility.GetActionId(
                "Game\"play\\Mode",
                "PlayerActions",
                "Move\"Fast");
            Assert.That(source, Does.Contain($" = {expectedId};"));
            Assert.That(source, Does.Contain("// FNV-1a32: Game\"play\\Mode/PlayerActions/Move\"Fast"));
            Assert.That(
                CountOccurrences(source, "public const int Game_play_Mode_Move_Fast"),
                Is.EqualTo(1),
                "Identical cross-player action schemas must be deduplicated.");
            Assert.That(source, Does.Contain("PlayerJoin_P0_JoinGame"));
            Assert.That(source, Does.Contain("PlayerJoin_P1_JoinGame"));
        }

        [Test]
        public void Generate_RejectsControlCharacterInjection()
        {
            InputConfiguration configuration = CreateCodegenConfiguration();
            configuration.PlayerSlots[0].Contexts[0].Bindings[0].ActionName = "Move\npublic class Injected";

            bool generated = InputConstantsCodeGenerator.TryGenerate(
                configuration,
                "Game.Input",
                out _,
                out string error);

            Assert.That(generated, Is.False);
            Assert.That(error, Does.Contain("control"));
        }

        [Test]
        public void Generate_SampleFixtureMatchesCheckedInConstants()
        {
            string packageRoot = Path.Combine(
                Application.dataPath,
                "ThirdParty",
                "CycloneGames",
                "CycloneGames.InputSystem");
            string fixturePath = Path.Combine(packageRoot, "Samples", "Fixtures", "input_config.yaml");
            string generatedPath = Path.Combine(packageRoot, "Samples", "Generated", "InputActions.cs");
            InputConfiguration configuration =
                YamlSerializer.Deserialize<InputConfiguration>(File.ReadAllBytes(fixturePath));

            bool generated = InputConstantsCodeGenerator.TryGenerate(
                configuration,
                "CycloneGames.InputSystem.Runtime.Generated",
                out string source,
                out string error);

            Assert.That(generated, Is.True, error);
            Assert.That(
                NormalizeLineEndings(File.ReadAllText(generatedPath, Encoding.UTF8)),
                Is.EqualTo(NormalizeLineEndings(source)));
        }

        [Test]
        public void Generate_RejectsDeterministicActionIdCollision()
        {
            const string firstAction = "ASXGBODWZ";
            const string secondAction = "AONYREHKX";
            Assert.That(
                InputHashUtility.GetActionId("Gameplay", "PlayerActions", firstAction),
                Is.EqualTo(InputHashUtility.GetActionId("Gameplay", "PlayerActions", secondAction)),
                "The fixture must remain a real FNV-1a collision.");

            InputConfiguration configuration = CreateCodegenConfiguration();
            ContextDefinitionConfig context = configuration.PlayerSlots[0].Contexts[0];
            context.Name = "Gameplay";
            context.Bindings[0].ActionName = firstAction;
            context.Bindings.Add(new ActionBindingConfig
            {
                Type = ActionValueType.Button,
                ActionName = secondAction,
                DeviceBindings = new List<string> { "<Keyboard>/b" },
                LongPressValueThreshold = 0.5f
            });

            bool generated = InputConstantsCodeGenerator.TryGenerate(
                configuration,
                "Game.Input",
                out _,
                out string error);

            Assert.That(generated, Is.False);
            Assert.That(error, Does.Contain("collision").IgnoreCase);
        }

        [TestCase("Game.Input; public class Injected")]
        [TestCase("Game..Input")]
        [TestCase("9Game.Input")]
        public void Generate_RejectsInvalidNamespace(string generatedNamespace)
        {
            bool generated = InputConstantsCodeGenerator.TryGenerate(
                CreateCodegenConfiguration(),
                generatedNamespace,
                out _,
                out string error);

            Assert.That(generated, Is.False);
            Assert.That(error, Is.Not.Empty);
        }

        [Test]
        public void ProjectPathResolution_RejectsTraversalEmptySegmentsAndZeroWidthText()
        {
            string projectRoot = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("N"));

            Assert.That(
                InputEditorFileUtility.TryResolveProjectAssetPath(
                    projectRoot,
                    "Assets/Generated/InputActions.cs",
                    out string resolved,
                    out string successError),
                Is.True,
                successError);
            Assert.That(resolved, Does.StartWith(Path.GetFullPath(Path.Combine(projectRoot, "Assets"))));

            Assert.That(
                InputEditorFileUtility.TryResolveProjectAssetPath(
                    projectRoot,
                    "Assets/../outside.cs",
                    out _,
                    out _),
                Is.False);
            Assert.That(
                InputEditorFileUtility.TryResolveProjectAssetPath(
                    projectRoot,
                    "Assets/Generated//InputActions.cs",
                    out _,
                    out _),
                Is.False);
            Assert.That(
                InputEditorFileUtility.TryResolveProjectAssetPath(
                    projectRoot,
                    "Assets/Generated/Zero\u200BWidth.cs",
                    out _,
                    out _),
                Is.False);
        }

        [Test]
        public void UserConfigPathResolution_RequiresPortableRelativeSegments()
        {
            string root = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("N"));

            Assert.That(
                InputEditorFileUtility.TryResolveUserConfigPath(
                    root,
                    "profiles/local",
                    "input.yaml",
                    out string resolved,
                    out string successError),
                Is.True,
                successError);
            Assert.That(resolved, Does.StartWith(Path.GetFullPath(root)));

            Assert.That(
                InputEditorFileUtility.TryResolveUserConfigPath(
                    root,
                    "profiles/../outside",
                    "input.yaml",
                    out _,
                    out _),
                Is.False);
            Assert.That(
                InputEditorFileUtility.TryResolveUserConfigPath(
                    root,
                    "profiles//local",
                    "input.yaml",
                    out _,
                    out _),
                Is.False);
            Assert.That(
                InputEditorFileUtility.TryResolveUserConfigPath(
                    root,
                    ".",
                    "input.yaml",
                    out _,
                    out _),
                Is.False);
        }

        [Test]
        public void TransactionalWrite_ReplacesTargetAndKeepsPreviousBytesInBackup()
        {
            string directory = Path.Combine(
                Path.GetTempPath(),
                "CycloneGames.InputSystem.EditorTests",
                Guid.NewGuid().ToString("N"));
            string target = Path.Combine(directory, "InputActions.cs");
            Directory.CreateDirectory(directory);
            File.WriteAllText(target, "old", new UTF8Encoding(false));

            try
            {
                bool written = InputEditorFileUtility.TryWriteBytesTransactional(
                    target,
                    new UTF8Encoding(false).GetBytes("new"),
                    out string backup,
                    out string error);

                Assert.That(written, Is.True, error);
                Assert.That(File.ReadAllText(target, Encoding.UTF8), Is.EqualTo("new"));
                Assert.That(File.Exists(backup), Is.True);
                Assert.That(File.ReadAllText(backup, Encoding.UTF8), Is.EqualTo("old"));

                bool writtenAgain = InputEditorFileUtility.TryWriteBytesTransactional(
                    target,
                    new UTF8Encoding(false).GetBytes("newer"),
                    out string secondBackup,
                    out string secondError);
                Assert.That(writtenAgain, Is.True, secondError);
                Assert.That(secondBackup, Is.EqualTo(backup));
                Assert.That(File.ReadAllText(target, Encoding.UTF8), Is.EqualTo("newer"));
                Assert.That(File.ReadAllText(secondBackup, Encoding.UTF8), Is.EqualTo("new"));
                Assert.That(Directory.GetFiles(directory, "*.bak").Length, Is.EqualTo(1));
            }
            finally
            {
                if (Directory.Exists(directory))
                {
                    Directory.Delete(directory, true);
                }
            }
        }

        [TestCase("input.yaml.bak")]
        [TestCase("input.yaml.tmp.deadbeef")]
        [TestCase("input.yaml.bak.tmp.deadbeef")]
        public void TransactionalWrite_RejectsReservedSidecarTargets(string fileName)
        {
            string directory = Path.Combine(
                Path.GetTempPath(),
                "CycloneGames.InputSystem.EditorTests",
                Guid.NewGuid().ToString("N"));
            string target = Path.Combine(directory, fileName);
            try
            {
                bool written = InputEditorFileUtility.TryWriteBytesTransactional(
                    target,
                    new byte[] { 1 },
                    out string backup,
                    out string error);

                Assert.That(written, Is.False);
                Assert.That(backup, Is.Null);
                Assert.That(error, Does.Contain("reserved"));
                Assert.That(File.Exists(target), Is.False);
            }
            finally
            {
                if (Directory.Exists(directory)) Directory.Delete(directory, true);
            }
        }

        private static InputConfiguration CreateCodegenConfiguration()
        {
            return new InputConfiguration
            {
                SchemaVersion = InputConfiguration.CurrentSchemaVersion,
                PlayerSlots = new List<PlayerSlotConfig>
                {
                    CreateSlot(0),
                    CreateSlot(1)
                }
            };
        }

        private static InputConfiguration CreateMinimalConfiguration()
        {
            return new InputConfiguration
            {
                SchemaVersion = InputConfiguration.CurrentSchemaVersion,
                PlayerSlots = new List<PlayerSlotConfig>
                {
                    new PlayerSlotConfig
                    {
                        PlayerId = 0,
                        Contexts = new List<ContextDefinitionConfig>
                        {
                            new ContextDefinitionConfig
                            {
                                Name = "Gameplay",
                                ActionMap = "PlayerActions",
                                BlocksLowerPriority = true,
                                Bindings = new List<ActionBindingConfig>
                                {
                                    new ActionBindingConfig
                                    {
                                        Type = ActionValueType.Vector2,
                                        ActionName = "Move",
                                        DeviceBindings = new List<string> { "<Gamepad>/leftStick" },
                                        UpdateMode = InputUpdateMode.Polling,
                                        LongPressValueThreshold = 0.5f
                                    }
                                }
                            }
                        }
                    }
                }
            };
        }

        private static PlayerSlotConfig CreateSlot(int playerId)
        {
            return new PlayerSlotConfig
            {
                PlayerId = playerId,
                JoinAction = new ActionBindingConfig
                {
                    Type = ActionValueType.Button,
                    ActionName = "JoinGame",
                    DeviceBindings = new List<string> { "<Gamepad>/start" },
                    LongPressValueThreshold = 0.5f
                },
                Contexts = new List<ContextDefinitionConfig>
                {
                    new ContextDefinitionConfig
                    {
                        Name = "Game\"play\\Mode",
                        ActionMap = "PlayerActions",
                        BlocksLowerPriority = true,
                        Bindings = new List<ActionBindingConfig>
                        {
                            new ActionBindingConfig
                            {
                                Type = ActionValueType.Vector2,
                                ActionName = "Move\"Fast",
                                DeviceBindings = new List<string> { "<Gamepad>/leftStick" },
                                UpdateMode = InputUpdateMode.Polling,
                                LongPressValueThreshold = 0.5f
                            }
                        }
                    }
                }
            };
        }

        private static int CountOccurrences(string value, string pattern)
        {
            int count = 0;
            int offset = 0;
            while ((offset = value.IndexOf(pattern, offset, StringComparison.Ordinal)) >= 0)
            {
                count++;
                offset += pattern.Length;
            }
            return count;
        }

        private static string NormalizeLineEndings(string value)
        {
            return value.Replace("\r\n", "\n").Replace('\r', '\n');
        }
    }
}
